/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.iesjandula.juegopokemon.windows;

import es.iesjandula.juegopokemon.classes.Pokemon;
import java.util.List;
import javax.swing.ImageIcon;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author 2DAM
 */
public class CombatWindow extends javax.swing.JFrame {
    private static Logger log = LogManager.getLogger();
    private final ImageIcon imagenAtaqueEspecial = new ImageIcon("src/main/resources/imagenesWidgets/imagenAtaqueEspecial.png");
    private final ImageIcon imagenAtaqueFisico = new ImageIcon("src/main/resources/imagenesWidgets/imagenAtaqueFisico.png");
    private Pokemon poke1;
    private Pokemon poke2;
    private List<Pokemon> listaPoke1;
    private List<Pokemon> listaPoke2;
    /**
     * Creates new form CombatWindow
     */
    public CombatWindow(Pokemon poke1,Pokemon poke2,List<Pokemon> listaPoke1,List<Pokemon> listaPoke2)
    {
        initComponents();
        this.poke1 = poke1;
        this.poke2 = poke2;
        this.listaPoke1 = listaPoke1;
        this.listaPoke2 = listaPoke2;
        this.botonAtaqueSimple1.setIcon(imagenAtaqueFisico);
        this.botonAtaqueEspecial.setIcon(imagenAtaqueEspecial);
        this.HPPoke1.setText(""+poke1.getHp());
        this.HPPoke2.setText(""+poke2.getHp());
        this.infoAtaqueF1.setText(poke1.getSimpleAttack());
        this.infoAtaqueF2.setText(poke2.getSimpleAttack());
        this.infoAtaqueS1.setText(poke1.getSpecialAttack());
        this.infoAtaqueS2.setText(poke2.getSpecialAttack());
        this.DamageSimple1.setText(""+poke1.getSimpleAttackDmg());
        this.DamageSimple2.setText(""+poke2.getSimpleAttackDmg());
        this.DamageSpecial1.setText(""+poke1.getSpecialAttackDmg());
        this.DamageSpecial2.setText(""+poke2.getSpecialAttackDmg());
        this.nombrePokemon1.setText(poke1.getName());
        this.nombrePokemon2.setText(poke2.getName());
        
        
    }
    public CombatWindow()
    {
        initComponents();
        this.botonAtaqueSimple1.setIcon(imagenAtaqueFisico);
        this.botonAtaqueEspecial.setIcon(imagenAtaqueEspecial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrePokemon1 = new javax.swing.JLabel();
        nombrePokemon2 = new javax.swing.JLabel();
        carta1 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        HPPoke1 = new javax.swing.JLabel();
        DamageSimple1 = new javax.swing.JLabel();
        infoVida1 = new javax.swing.JLabel();
        infoAtaqueS1 = new javax.swing.JLabel();
        DamageSpecial1 = new javax.swing.JLabel();
        infoAtaqueF1 = new javax.swing.JLabel();
        HPPoke2 = new javax.swing.JLabel();
        DamageSimple2 = new javax.swing.JLabel();
        infoVida2 = new javax.swing.JLabel();
        infoAtaqueS2 = new javax.swing.JLabel();
        DamageSpecial2 = new javax.swing.JLabel();
        infoAtaqueF2 = new javax.swing.JLabel();
        infpTurnos = new javax.swing.JLabel();
        botonAtaqueEspecial = new javax.swing.JLabel();
        botonAtaqueSimple1 = new javax.swing.JLabel();
        turnoJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombrePokemon1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nombrePokemon1.setText("jLabel1");

        nombrePokemon2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nombrePokemon2.setText("jLabel1");

        carta1.setText("jLabel1");

        carta2.setText("jLabel1");

        HPPoke1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        HPPoke1.setText("jLabel3");

        DamageSimple1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        DamageSimple1.setText("jLabel3");

        infoVida1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoVida1.setForeground(new java.awt.Color(0, 180, 0));
        infoVida1.setText("Vida:");

        infoAtaqueS1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoAtaqueS1.setForeground(new java.awt.Color(180, 90, 0));
        infoAtaqueS1.setText("Ataque Especial:");

        DamageSpecial1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        DamageSpecial1.setText("jLabel3");

        infoAtaqueF1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoAtaqueF1.setForeground(new java.awt.Color(180, 0, 0));
        infoAtaqueF1.setText("Ataque Fisico:");

        HPPoke2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        HPPoke2.setText("jLabel3");

        DamageSimple2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        DamageSimple2.setText("jLabel3");

        infoVida2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoVida2.setForeground(new java.awt.Color(0, 180, 0));
        infoVida2.setText("Vida:");

        infoAtaqueS2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoAtaqueS2.setForeground(new java.awt.Color(180, 90, 0));
        infoAtaqueS2.setText("Ataque Especial:");

        DamageSpecial2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        DamageSpecial2.setText("jLabel3");

        infoAtaqueF2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoAtaqueF2.setForeground(new java.awt.Color(180, 0, 0));
        infoAtaqueF2.setText("Ataque Fisico:");

        infpTurnos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infpTurnos.setText("Turnos");

        botonAtaqueEspecial.setText("jLabel1");

        botonAtaqueSimple1.setText("jLabel1");

        turnoJugador.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        turnoJugador.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(nombrePokemon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombrePokemon2)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoVida1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HPPoke1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoAtaqueF1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DamageSimple1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoAtaqueS1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DamageSpecial1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonAtaqueSimple1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonAtaqueEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(turnoJugador)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(infpTurnos)
                                .addGap(150, 150, 150)))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoAtaqueS2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DamageSpecial2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(infoVida2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HPPoke2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(infoAtaqueF2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DamageSimple2)))
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePokemon1)
                    .addComponent(nombrePokemon2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HPPoke1)
                                .addComponent(infoVida1))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DamageSimple1)
                                .addComponent(infoAtaqueF1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DamageSpecial1)
                                .addComponent(infoAtaqueS1)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HPPoke2)
                                .addComponent(infoVida2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DamageSimple2)
                                .addComponent(infoAtaqueF2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(infoAtaqueS2)
                                .addComponent(DamageSpecial2))
                            .addGap(16, 16, 16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(infpTurnos)
                        .addGap(18, 18, 18)
                        .addComponent(turnoJugador)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAtaqueSimple1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAtaqueEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CombatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DamageSimple1;
    private javax.swing.JLabel DamageSimple2;
    private javax.swing.JLabel DamageSpecial1;
    private javax.swing.JLabel DamageSpecial2;
    private javax.swing.JLabel HPPoke1;
    private javax.swing.JLabel HPPoke2;
    private javax.swing.JLabel botonAtaqueEspecial;
    private javax.swing.JLabel botonAtaqueSimple1;
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel infoAtaqueF1;
    private javax.swing.JLabel infoAtaqueF2;
    private javax.swing.JLabel infoAtaqueS1;
    private javax.swing.JLabel infoAtaqueS2;
    private javax.swing.JLabel infoVida1;
    private javax.swing.JLabel infoVida2;
    private javax.swing.JLabel infpTurnos;
    private javax.swing.JLabel nombrePokemon1;
    private javax.swing.JLabel nombrePokemon2;
    private javax.swing.JLabel turnoJugador;
    // End of variables declaration//GEN-END:variables
}
